SELECT CENTRE_SHOP_IW.SHOP_NO, SHOP_IW.SHOP_NAME, COUNT(CENTRE_IW.CENTRE_CODE) "CENTRES" 
FROM CENTRE_SHOP_IW 
INNER JOIN SHOP_IW ON CENTRE_SHOP_IW.SHOP_NO = SHOP_IW.SHOP_NO 
INNER JOIN CENTRE_IW ON CENTRE_SHOP_IW.CENTRE_CODE = CENTRE_IW.CENTRE_CODE 
GROUP BY CENTRE_SHOP_IW.SHOP_NO 
HAVING COUNT(CENTRES)>2